export const GAMES_DATA = [
    {
        id: "1",
        title: "Dead by Daylight",
        imageSource: require("./assets/images/DeadByDaylight.png"),
        description: "Recommended by your friend",
        discount: 70,
        price: 18,
        platforms: ["windows", "macos"],
        sales: 500000,
        releaseDate: "2022-06-15",
        isEarlyAccess: false
    },
    {
        id: "2",
        title: "Cyberpunk 2077",
        imageSource: require("./assets/images/cyberpunk.png"),
        description: "New expansion available",
        discount: 50,
        price: 60,
        platforms: ["windows", "macos"],
        sales: 1000000,
        releaseDate: "2020-12-10",
        isEarlyAccess: false
    },
    {
        id: "3",
        title: "The Witcher 3",
        imageSource: require("./assets/images/witcher3.png"),
        description: "Best RPG of all time",
        discount: 80,
        price: 40,
        platforms: ["windows", "macos"],
        sales: 2000000,
        releaseDate: "2015-05-19",
        isEarlyAccess: false
    },
    {
        id: "4",
        title: "Stalker 2",
        imageSource: require("./assets/images/stalker.png"),
        description: "A long-awaited continuation of the Stalker series, offering an immersive post-apocalyptic experience in the Chernobyl Exclusion Zone.",
        discount: 30,
        price: 60,
        platforms: ["windows"],
        sales: 5000000,
        releaseDate: "2024-11-20",
        isEarlyAccess: false
    },
    {
        id: "5",
        title: "Apex Legends",
        imageSource: require("./assets/images/apex.png"),
        description: "Free-to-play battle royale game with a fast-paced gameplay.",
        discount: 0,
        price: 0,
        platforms: ["windows", "macos"],
        sales: 30000000,
        releaseDate: "2019-02-04",
        isEarlyAccess: false
    },
    {
        id: "6",
        title: "Hunt: Showdown",
        imageSource: require("./assets/images/hunt.png"),
        description: "Intense multiplayer PvPvE shooter with unique survival mechanics.",
        discount: 20,
        price: 30,
        platforms: ["windows"],
        sales: 1500000,
        releaseDate: "2018-08-27",
        isEarlyAccess: false
    },
    {
        id: "7",
        title: "Among Us",
        imageSource: require("./assets/images/amongus.png"),
        description: "Multiplayer social deduction game with fun mechanics.",
        discount: 0,
        price: 0,
        platforms: ["windows"],
        sales: 10000000,
        releaseDate: "2018-11-16",
        isEarlyAccess: false
    },
    {
        id: "8",
        title: "The Forest",
        imageSource: require("./assets/images/forest.png"),
        description: "Survival horror game set on a mysterious island.",
        discount: 50,
        price: 20,
        platforms: ["windows", "macos"],
        sales: 8000000,
        releaseDate: "2018-04-30",
        isEarlyAccess: false
    },
    {
        id: "9",
        title: "Valhallah",
        imageSource: require("./assets/images/valhallah.png"),
        description: "An immersive Norse mythology-based action RPG.",
        discount: 40,
        price: 45,
        platforms: ["macos"],
        sales: 300000,
        releaseDate: "2023-03-01",
        isEarlyAccess: false
    },
    {
        id: "10",
        title: "Call of Duty: Warzone",
        imageSource: require("./assets/images/codwarzone.png"),
        description: "Free-to-play battle royale with intense combat.",
        discount: 0,
        price: 0,
        platforms: ["windows"],
        sales: 25000000,
        releaseDate: "2020-03-10",
        isEarlyAccess: false
    },
    {
        id: "11",
        title: "Rust",
        imageSource: require("./assets/images/rust.png"),
        description: "A multiplayer survival game in a harsh environment.",
        discount: 25,
        price: 30,
        platforms: ["windows"],
        sales: 15000000,
        releaseDate: "2013-12-11",
        isEarlyAccess: true
    },
    {
        id: "12",
        title: "Subnautica",
        imageSource: require("./assets/images/subnautica.png"),
        description: "An open-world survival game set under the ocean.",
        discount: 60,
        price: 25,
        platforms: ["windows", "macos"],
        sales: 7000000,
        releaseDate: "2018-01-23",
        isEarlyAccess: false
    },
    {
        id: "13",
        title: "Minecraft",
        imageSource: require("./assets/images/minecraft.png"),
        description: "The most popular sandbox game, build anything you can imagine.",
        discount: 0,
        price: 25,
        platforms: ["windows", "macos"],
        sales: 200000000,
        releaseDate: "2011-11-18",
        isEarlyAccess: false
    },
    {
        id: "14",
        title: "FIFA 23",
        imageSource: require("./assets/images/fifa23.png"),
        description: "The latest installment of the FIFA soccer franchise.",
        discount: 15,
        price: 50,
        platforms: ["windows"],
        sales: 5000000,
        releaseDate: "2022-09-30",
        isEarlyAccess: false
    },
    {
        id: "15",
        title: "Kerbal Space Program 2",
        imageSource: require("./assets/images/kerbal2.png"),
        description: "A fun and educational space exploration game.",
        discount: 0,
        price: 40,
        platforms: ["macos"],
        sales: 100000,
        releaseDate: "2023-02-23",
        isEarlyAccess: true
    },
    {
        id: "16",
        title: "Fall Guys",
        imageSource: require("./assets/images/fallguys.png"),
        description: "A fun and chaotic battle royale game with obstacle courses.",
        discount: 50,
        price: 20,
        platforms: ["windows"],
        sales: 10000000,
        releaseDate: "2020-08-04",
        isEarlyAccess: false
    },
    {
        id: "17",
        title: "Satisfactory",
        imageSource: require("./assets/images/satisfactory.png"),
        description: "A factory-building game with a focus on exploration.",
        discount: 35,
        price: 30,
        platforms: ["windows", "macos"],
        sales: 2000000,
        releaseDate: "2019-03-19",
        isEarlyAccess: true
    },
    {
        id: "18",
        title: "Loop Hero",
        imageSource: require("./assets/images/loophiero.png"),
        description: "A rogue-like adventure with an innovative loop system.",
        discount: 50,
        price: 15,
        platforms: ["windows"],
        sales: 1000000,
        releaseDate: "2021-03-04",
        isEarlyAccess: false
    },
    {
        id: "19",
        title: "Phasmophobia",
        imageSource: require("./assets/images/phasmophobia.png"),
        description: "Co-op horror game where you hunt ghosts in various locations.",
        discount: 10,
        price: 14,
        platforms: ["windows", "macos"],
        sales: 5000000,
        releaseDate: "2020-09-18",
        isEarlyAccess: false
    },
    {
        id: "20",
        title: "Factorio",
        imageSource: require("./assets/images/factorio.png"),
        description: "A game focused on resource gathering and factory automation.",
        discount: 0,
        price: 30,
        platforms: ["windows"],
        sales: 2000000,
        releaseDate: "2020-08-14",
        isEarlyAccess: false
    }
];
